### ISSUE TITLE
ДЗ

### ISSUE THREAD

**Issue by maratkhambelov** [maratkhambelov/ReadLater#1]
Не могу сделать чтобы заработал local storage. У меня не удаляются файлы из local storage. Помогите. 
Иногда Выскакивает либо ошибка о том, что remove это не функция. Либо выскакивает что-то связанное с промисом

https://github.com/maratkhambelov/ReadLater/blob/0fda6f97bb01f1c918268f70209a455c02642178/frontend/src/js/app.js#L72-L87

**Comment by coursar** [comment]
см #2
