### ISSUE TITLE
Этот файл я так понимаю не нужен? Что тут происходит можешь объяснить? :)

### ISSUE THREAD

**Issue by lerucom** [maratkhambelov/ReadLater#4]
@maratkhambelov https://github.com/maratkhambelov/ReadLater/blob/6ab593ad4e72cbbcae247ea4994469aa6c8943be/requests.http#L1-L30

**Comment by coursar** [comment]
Мы же разбирали на лекции. Это просто файл WebStorm, который позволяет отправлять HTTP-запросы без необходимости написания кода.
